export const BOOK_LIST = [
  {
    bookId: 1,
    bookUuid: 'ee4f66f9-9cf4-4b28-90f4-f71d0ecba021',
    favoriteName: 'Lecue',
    title: '레큐의 탄생을 축하해!',
    bookDate: '2024.01.12',
    bookBackgroundColor: 1,
    noteNum: 28760,
  },
  {
    bookId: 2,
    bookUuid: 'ee4f66f9-9cf4-4b28-90f4-f71d0ecba022',
    favoriteName: '비니',
    title: '비니 귀여운거 축하해',
    bookDate: '2024.01.12',
    bookBackgroundColor: 1,
    noteNum: 29983,
  },
  {
    bookId: 3,
    bookUuid: 'ee4f66f9-9cf4-4b28-90f4-f71d0ecba023',
    favoriteName: '쩡우',
    title: '큐비 천재 쩡우 그냥 축하해',
    bookDate: '2024.01.12',
    bookBackgroundColor: 1,
    noteNum: 18293,
  },
  {
    bookId: 4,
    bookUuid: 'ee4f66f9-9cf4-4b28-90f4-f71d0ecba024',
    favoriteName: '아루밍',
    title: '세계 최고 리드 아루밍 사랑해',
    bookDate: '2024.01.12',
    bookBackgroundColor: 1,
    noteNum: 9987,
  },
  {
    bookId: 5,
    bookUuid: 'ee4f66f9-9cf4-4b28-90f4-f71d0ecba025',
    favoriteName: '도리',
    title: '내일 집 가는거 축하해',
    bookDate: '2024.01.12',
    bookBackgroundColor: 1,
    noteNum: 1022,
  },
  {
    bookId: 6,
    bookUuid: 'ee4f66f9-9cf4-4b28-90f4-f71d0ecba026',
    favoriteName: '큐비',
    title: '세계최고 큐비 짱짱ㅋ',
    bookDate: '2024.01.12',
    bookBackgroundColor: 1,
    noteNum: 999999,
  },
  {
    bookId: 7,
    bookUuid: 'ee4f66f9-9cf4-4b28-90f4-f71d0ecba027',
    favoriteName: '레큐',
    title: '역시 레큐가 최고지ㅋ',
    bookDate: '2024.01.12',
    bookBackgroundColor: 1,
    noteNum: 100,
  },
];
export const NOTE_LIST = [
  {
    noteId: 0,
    favoriteName: 'Lecue',
    title: '큐비들이 짱임ㅋㅋ',
    noteDate: '2024.01.12',
    content:
      '큐비들 사랑해 큐비들 최고 큐비들 완전 귀여움 큐비들밖에 없다 내 사랑 큐비들 알러뷰 다들 끝까지 파이팅 사랑해앸!!!!!!',
    noteTextColor: 0,
    noteBackgroundColor: 0,
    noteBackgroundImage: '',
  },
  {
    noteId: 1,
    favoriteName: 'Lecue',
    title: '어쩌면 큐기도 짱 ㅋㅋ',
    noteDate: '2024.01.12',
    content:
      '큐기들 사랑해 큐기들 최고 큐기들 완전 귀여움 큐기들밖에 없다 내 사랑 큐기들 알러뷰 다들 끝까지 파이팅 사랑해앸!!!!!!',
    noteTextColor: 0,
    noteBackgroundColor: 1,
    noteBackgroundImage: '',
  },
  {
    noteId: 2,
    favoriteName: 'Lecue',
    title: '어쩌면 큐디도 짱 ㅋㅋ',
    noteDate: '2024.01.12',
    content:
      '큐디들 사랑해 큐디들 최고 큐디들 완전 귀여움 큐디들밖에 없다 내 사랑 큐디들 알러뷰 다들 끝까지 파이팅 사랑해앸!!!!!!',
    noteTextColor: 0,
    noteBackgroundColor: 2,
    noteBackgroundImage: '',
  },
  {
    noteId: 3,
    favoriteName: 'Lecue',
    title: '큐버도 짱 해드려요ㅎ',
    noteDate: '2024.01.12',
    content:
      '큐버들 사랑해 큐버들 최고 큐버들 완전 귀여움 큐버들밖에 없다 내 사랑 큐버들 알러뷰 다들 끝까지 파이팅 사랑해앸!!!!!!',
    noteTextColor: 1,
    noteBackgroundColor: 3,
    noteBackgroundImage: '',
  },
  {
    noteId: 4,
    favoriteName: 'Lecue',
    title: '큐비들이 짱임ㅋㅋ',
    noteDate: '2024.01.12',
    content:
      '큐비들 사랑해 큐비들 최고 큐비들 완전 귀여움 큐비들밖에 없다 내 사랑 큐비들 알러뷰 다들 끝까지 파이팅 사랑해앸!!!!!!',
    noteTextColor: 0,
    noteBackgroundColor: 4,
    noteBackgroundImage: '',
  },
  {
    noteId: 5,
    favoriteName: 'Lecue',
    title: '큐비들이 짱임ㅋㅋ',
    noteDate: '2024.01.12',
    content:
      '큐비들 사랑해 큐비들 최고 큐비들 완전 귀여움 큐비들밖에 없다 내 사랑 큐비들 알러뷰 다들 끝까지 파이팅 사랑해앸!!!!!!',
    noteTextColor: 0,
    noteBackgroundColor: 5,
    noteBackgroundImage: '',
  },
  {
    noteId: 6,
    favoriteName: 'Lecue',
    title: '큐비들이 짱임ㅋㅋ',
    noteDate: '2024.01.12',
    content:
      '큐비들 사랑해 큐비들 최고 큐비들 완전 귀여움 큐비들밖에 없다 내 사랑 큐비들 알러뷰 다들 끝까지 파이팅 사랑해앸!!!!!!',
    noteTextColor: 1,
    noteBackgroundColor: 6,
    noteBackgroundImage: '',
  },
  {
    noteId: 7,
    favoriteName: 'Lecue',
    title: '큐비들이 짱임ㅋㅋ',
    noteDate: '2024.01.12',
    content:
      '큐비들 사랑해 큐비들 최고 큐비들 완전 귀여움 큐비들밖에 없다 내 사랑 큐비들 알러뷰 다들 끝까지 파이팅 사랑해앸!!!!!!',
    noteTextColor: 0,
    noteBackgroundColor: 7,
    noteBackgroundImage: '',
  },
  {
    noteId: 8,
    favoriteName: 'Lecue',
    title: '큐비들이 짱임ㅋㅋ',
    noteDate: '2024.01.12',
    content:
      '큐비들 사랑해 큐비들 최고 큐비들 완전 귀여움 큐비들밖에 없다 내 사랑 큐비들 알러뷰 다들 끝까지 파이팅 사랑해앸!!!!!!',
    noteTextColor: 0,
    noteBackgroundColor: 8,
    noteBackgroundImage: '',
  },
  {
    noteId: 9,
    favoriteName: 'Lecue',
    title: '큐비들이 짱임ㅋㅋ',
    noteDate: '2024.01.12',
    content:
      '큐비들 사랑해 큐비들 최고 큐비들 완전 귀여움 큐비들밖에 없다 내 사랑 큐비들 알러뷰 다들 끝까지 파이팅 사랑해앸!!!!!!',
    noteTextColor: 1,
    noteBackgroundColor: 9,
    noteBackgroundImage: '',
  },
  {
    noteId: 10,
    favoriteName: 'Lecue',
    title: '큐비들이 짱임ㅋㅋ',
    noteDate: '2024.01.12',
    content:
      '큐비들 사랑해 큐비들 최고 큐비들 완전 귀여움 큐비들밖에 없다 내 사랑 큐비들 알러뷰 다들 끝까지 파이팅 사랑해앸!!!!!!',
    noteTextColor: 0,
    noteBackgroundColor: 10,
    noteBackgroundImage: '',
  },
  {
    noteId: 11,
    favoriteName: 'Lecue',
    title: '큐비들이 짱임ㅋㅋ',
    noteDate: '2024.01.12',
    content:
      '큐비들 사랑해 큐비들 최고 큐비들 완전 귀여움 큐비들밖에 없다 내 사랑 큐비들 알러뷰 다들 끝까지 파이팅 사랑해앸!!!!!!',
    noteTextColor: 0,
    noteBackgroundColor: 11,
    noteBackgroundImage: '',
  },
  {
    noteId: 12,
    favoriteName: 'Lecue',
    title: '큐비들이 짱임ㅋㅋ',
    noteDate: '2024.01.12',
    content:
      '큐비들 사랑해 큐비들 최고 큐비들 완전 귀여움 큐비들밖에 없다 내 사랑 큐비들 알러뷰 다들 끝까지 파이팅 사랑해앸!!!!!!',
    noteTextColor: 1,
    noteBackgroundColor: -1,
    noteBackgroundImage:
      'https://lequu-server-bucket.s3.ap-northeast-2.amazonaws.com/notes/background_image/912ac7e2-672a-4f26-b115-b90cda4d7cc3.jpg',
  },
  {
    noteId: 13,
    favoriteName: 'Lecue',
    title: '큐비들이 짱임ㅋㅋ',
    noteDate: '2024.01.12',
    content:
      '큐비들 사랑해 큐비들 최고 큐비들 완전 귀여움 큐비들밖에 없다 내 사랑 큐비들 알러뷰 다들 끝까지 파이팅 사랑해앸!!!!!!',
    noteTextColor: 0,
    noteBackgroundColor: -1,
    noteBackgroundImage:
      'https://lequu-server-bucket.s3.ap-northeast-2.amazonaws.com/notes/background_image/469456ec-5894-4014-8b90-332d453217ba.jpg',
  },
  {
    noteId: 14,
    favoriteName: 'Lecue',
    title: '큐비들이 짱임ㅋㅋ',
    noteDate: '2024.01.12',
    content:
      '큐비들 사랑해 큐비들 최고 큐비들 완전 귀여움 큐비들밖에 없다 내 사랑 큐비들 알러뷰 다들 끝까지 파이팅 사랑해앸!!!!!!',
    noteTextColor: 1,
    noteBackgroundColor: -1,
    noteBackgroundImage:
      'https://lequu-server-bucket.s3.ap-northeast-2.amazonaws.com/notes/background_image/676c2ca3-f868-423f-8000-a0bcb67dc797.jpg',
  },
];
